targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          constructor: ""
          field_rename: snake
          create_factory: true
          create_to_json: true
          create_field_map: true
