// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    defguardInstances,
    locations,
  ];
  late final Shape0 defguardInstances = Shape0(
    source: i0.VersionedTable(
      entityName: 'defguard_instances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 locations = Shape1(
    source: i0.VersionedTable(
      entityName: 'locations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_1,
        _column_15,
        _column_10,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uuid =>
      columnsByName['uuid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proxyUrl =>
      columnsByName['proxy_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get poolingToken =>
      columnsByName['pooling_token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get clientTrafficPolicy =>
      columnsByName['client_traffic_policy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get enterpriseEnabled =>
      columnsByName['enterprise_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get pubKey =>
      columnsByName['pub_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privateKey =>
      columnsByName['private_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get mfaKeysStored =>
      columnsByName['mfa_keys_stored']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uuid',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'proxy_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'username',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pooling_token',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'client_traffic_policy',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<bool> _column_9(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'enterprise_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("enterprise_enabled" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pub_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'private_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_12(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'mfa_keys_stored',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("mfa_keys_stored" IN (0, 1))',
      ),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get instance =>
      columnsByName['instance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get networkId =>
      columnsByName['network_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pubKey =>
      columnsByName['pub_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endpoint =>
      columnsByName['endpoint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get allowedIps =>
      columnsByName['allowed_ips']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dns =>
      columnsByName['dns']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get mfaEnabled =>
      columnsByName['mfa_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get trafficMethod =>
      columnsByName['traffic_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mfaMethod =>
      columnsByName['mfa_method']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get keepAliveInterval =>
      columnsByName['keep_alive_interval']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get locationMfaMode =>
      columnsByName['location_mfa_mode']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'instance',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES defguard_instances (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'network_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'address',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'endpoint',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'allowed_ips',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dns',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_19(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'mfa_enabled',
      aliasedName,
      true,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("mfa_enabled" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'traffic_method',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mfa_method',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'keep_alive_interval',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'location_mfa_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    defguardInstances,
    locations,
  ];
  late final Shape2 defguardInstances = Shape2(
    source: i0.VersionedTable(
      entityName: 'defguard_instances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 locations = Shape1(
    source: i0.VersionedTable(
      entityName: 'locations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_1,
        _column_15,
        _column_10,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uuid =>
      columnsByName['uuid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proxyUrl =>
      columnsByName['proxy_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get poolingToken =>
      columnsByName['pooling_token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get clientTrafficPolicy =>
      columnsByName['client_traffic_policy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get enterpriseEnabled =>
      columnsByName['enterprise_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get pubKey =>
      columnsByName['pub_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privateKey =>
      columnsByName['private_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get mfaKeysStored =>
      columnsByName['mfa_keys_stored']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get openidDisplayName =>
      columnsByName['openid_display_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'openid_display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    defguardInstances,
    locations,
  ];
  late final Shape2 defguardInstances = Shape2(
    source: i0.VersionedTable(
      entityName: 'defguard_instances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 locations = Shape3(
    source: i0.VersionedTable(
      entityName: 'locations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_1,
        _column_15,
        _column_10,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get instance =>
      columnsByName['instance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get networkId =>
      columnsByName['network_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pubKey =>
      columnsByName['pub_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endpoint =>
      columnsByName['endpoint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get allowedIps =>
      columnsByName['allowed_ips']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dns =>
      columnsByName['dns']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get mfaEnabled =>
      columnsByName['mfa_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get trafficMethod =>
      columnsByName['traffic_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mfaMethod =>
      columnsByName['mfa_method']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get keepAliveInterval =>
      columnsByName['keep_alive_interval']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get locationMfaMode =>
      columnsByName['location_mfa_mode']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get postureCheckRequired =>
      columnsByName['posture_check_required']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<bool> _column_25(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'posture_check_required',
      aliasedName,
      true,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("posture_check_required" IN (0, 1))',
      ),
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    defguardInstances,
    locations,
  ];
  late final Shape4 defguardInstances = Shape4(
    source: i0.VersionedTable(
      entityName: 'defguard_instances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 locations = Shape5(
    source: i0.VersionedTable(
      entityName: 'locations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_26,
        _column_38,
        _column_39,
        _column_27,
        _column_40,
        _column_35,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uuid =>
      columnsByName['uuid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proxyUrl =>
      columnsByName['proxy_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get clientTrafficPolicy =>
      columnsByName['client_traffic_policy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enterpriseEnabled =>
      columnsByName['enterprise_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pubKey =>
      columnsByName['pub_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mfaKeysStored =>
      columnsByName['mfa_keys_stored']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get openidDisplayName =>
      columnsByName['openid_display_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uuid',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'proxy_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'username',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'client_traffic_policy',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enterprise_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (enterprise_enabled IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pub_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mfa_keys_stored',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (mfa_keys_stored IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'openid_display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get instance =>
      columnsByName['instance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get networkId =>
      columnsByName['network_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pubKey =>
      columnsByName['pub_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endpoint =>
      columnsByName['endpoint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get allowedIps =>
      columnsByName['allowed_ips']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dns =>
      columnsByName['dns']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mfaEnabled =>
      columnsByName['mfa_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get trafficMethod =>
      columnsByName['traffic_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mfaMethod =>
      columnsByName['mfa_method']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get keepAliveInterval =>
      columnsByName['keep_alive_interval']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get locationMfaMode =>
      columnsByName['location_mfa_mode']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get postureCheckRequired =>
      columnsByName['posture_check_required']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'instance',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES defguard_instances(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'network_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'address',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'endpoint',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'allowed_ips',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dns',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mfa_enabled',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (mfa_enabled IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'traffic_method',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mfa_method',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'keep_alive_interval',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'location_mfa_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'posture_check_required',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (posture_check_required IN (0, 1))',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
