name: Run Flutter Lint and Tests

on:
  push:
    branches:
      - main
      - dev
      - "release/**"
      - "hotfix/**"
    paths-ignore: &ignored_paths
      - "*.md"
      - "LICENSE"
      - "flake.*"
  pull_request:
    branches:
      - main
      - dev
      - "release/**"
      - "hotfix/**"
    paths-ignore: *ignored_paths

jobs:
  lint:
    name: Lint and test
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: "recursive"

      - name: Scan code with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH,MEDIUM"
          scanners: "vuln"

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.47.2

      - name: get deps
        run: flutter pub get

      - name: check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: run lint
        run: flutter analyze

  # test-ios:
  #   name: Run iOS tests
  #   runs-on: [self-hosted, macOS, native]
  #   needs: lint
  #   defaults:
  #     run:
  #       working-directory: ./client/ios

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7
  #       with:
  #         submodules: "recursive"

  #     - name: setup flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         flutter-version: 3.47.2

  #     - name: Enable Swift Package Manager
  #       run: flutter config --enable-swift-package-manager

  #     - name: get deps
  #       run: flutter pub get

  #     - name: Create BoringTun directory
  #       run: mkdir -p VPNExtension/BoringTun

  #     - name: Generate boringtun bindings
  #       run: cd boringtun && ./bindings.sh

  #     # - name: build project
  #     #   run: flutter build ios

  #     - name: run plugin tests
  #       run: xcodebuild test -workspace Runner.xcworkspace -scheme Runner
