name: "Release"

on:
  workflow_call:

jobs:
  create-release:
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          draft: true
          files: |
            ./artifacts/Defguard.ipa
            ./artifacts/Defguard.aab
            ./artifacts/Defguard.apk

  create-sbom:
    needs: [create-release]
    uses: ./.github/workflows/sbom.yaml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
