name: "Release"

on:
  workflow_call:

jobs:
  create-release:
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3
        with:
          draft: true
          files: |
            ./artifacts/Defguard.ipa
            ./artifacts/Defguard.aab
            ./artifacts/Defguard.apk

  create-sbom:
    needs: [create-release]
    uses: ./.github/workflows/sbom.yaml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
